/*EJERCICIO 6*/
CREATE OR REPLACE PROCEDURE ver_trabajador
IS 
    CURSOR C_TRABAJADOR IS
    SELECT APELLIDO1, FECHANAC
    FROM TRABAJADORES
    ORDER BY APELLIDO1; --No puede ir en el BEGIN porque devuelve más de una fila, por eso abrimos un CURSOR
  REG_TRABAJADOR C_TRBAJADOR %ROWTYPE;
BEGIN
  OPEN C_TRABAJADOR;
  LOOP 
    FETCH C_TRABAJADOR INTO REG_TRABAJADOR;
    DBMS_OUTPUT.PUT_LINE('Apellido: ' || REG_TRABAJADOR.APELLIDO1);
    DBMS_OUTPUT.PUT_LINE('Fecha nac:' ||TO_CHAR( REG_TRABAJADOR.FECHANAC));
    EXIT WHEN C_TRABAJADOR %NOTFOUND;
  END LOOP;
  CLOSE C_TRABAJADOR;
END;

