/*EJERCICIO 1*/
DECLARE
V_NOM VARCHAR2(15):='Pepe';
BEGIN DBMS_OUTPUT.PUT_LINE('Hola Mundo '|| V_NOM);
END;


/*EJERCICIO 2*/
DECLARE
IDENT NUMBER(2);
BEGIN 
SELECT MAX(ID)INTO IDENT FROM CENTROS;
IF ID=NULL THEN ID=0;
DBMS_OUTPUT.PUT_LINE('El ultimo identificador de centro es: '|| IDENT);
END;

