/*EJERCICIO 1*/
DECLARE
V_NOM VARCHAR2(15):='Pepe';
BEGIN DBMS_OUTPUT.PUT_LINE('Hola Mundo '|| V_NOM);
END;


/*EJERCICIO 2 y 3*/
DECLARE
IDENT CENTROS.ID%TYPE; --para saber el tipo
BEGIN 
SELECT MAX(id)INTO IDENT FROM CENTROS;
IF IDENT IS NOT NULL THEN  DBMS_OUTPUT.PUT_LINE('El ultimo identificador de centro es: '|| IDENT);
ELSE DBMS_OUTPUT.PUT_LINE('No hay centros');
END IF;
END;

SET SERVEROUTPUT ON --EN CADA SESION INICIARLO

DECLARE
IDENT CENTROS.NOMBRE%TYPE; --para saber el tipo
BEGIN 
SELECT NOMBRE INTO IDENT FROM CENTROS;
IF  SQL%FOUND THEN  DBMS_OUTPUT.PUT_LINE('El ultimo identificador de centro es: '|| IDENT); 
END IF;
EXCEPTION
      WHEN no_data_found THEN
      DBMS_OUTPUT.PUT_LINE('No hay centros');
      WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('Error inesperado');
END;


